# This is a basic workflow to help you get started with Actions

name: thanks-push

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   

  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 my-job:
  # This workflow contains a single job called "build"
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      

     

      # Runs a set of commands using the runners shell
      - name: my-step
        run: |
          echo "thanks for collaburating"
          
